### ISSUE TITLE
connected_chest compatibility changes

### ISSUE THREAD

**Issue by HybridDog** [DustyBagel/hopper_compat#5]
We have recently changed the connected_chest and facedeer hopper (https://github.com/minetest-mods/hopper/) mods to make them compatible with each other. (This compatibility between connected_chest and hopper currently only works with facedeer's version and not TenPlus1's version.)
Maybe hopper_compat needs to be changed now, too.

**Comment by DustyBagel** [comment]
So, the very messy code in this mod for that compatability is no longer required? Well, that is actually a relief because it needs to be cleaned up anyway, and I didn't really feel like doing that at the moment. I suppose I should make it work for tenplus1's version then? Unless you are already working on it?

Anyway, thanks for letting me know, I appreciate it.

**Comment by HybridDog** [comment]
Sorry for the late response.
I'm not working on hopper compatibility (except code reviews at my mods). I think the compatibility code in hopper_compat is no longer needed. If tenplus1's version should be supported, too, it may be easier to adopt [the Pull Request from facedeer hopper](https://github.com/minetest-mods/hopper/pull/26) to tenplus1's hopper mod than to edit the hopper_compat mod if the code of both hopper mods is similar enough.

**Comment by DustyBagel** [comment]
Good point, I was getting ready to start adding the compatibility for tenplus1's hopper mod but if just opening a similar pr to tenplus1's version is easier than I will consider doing that instead.

I reviewed the changes to facedeer's hopper mod, and I agree that my compatibility code is now unnecessary and have removed it.

Don't worry about the late response. I'd rather have a late one rather than none at all. :)
